# Generated by Django 4.2.5 on 2023-09-15 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaArtigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('sinopse', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('envio_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mostra', models.BooleanField(default=True)),
                ('Capa', models.ImageField(blank=True, upload_to='fotos/%y/%m/%d/')),
                ('pdf', models.FileField(blank=True, upload_to='Artigos/%y/%m/%d/')),
                ('Usuario_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Artigo.categoriaartigos')),
            ],
        ),
    ]
