# Generated by Django 4.2.5 on 2023-09-15 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artigo.categoriaartigos'),
        ),
    ]
