# Generated by Django 4.2.5 on 2023-09-16 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Artigo', '0002_alter_artigo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='Usuario_id',
        ),
        migrations.AddField(
            model_name='artigo',
            name='Usuario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
